lostCTRL/force-app/main/default/objects/Product_images__c/Product_images__c.object-meta.xml
<CustomObject>
    <label>Product images</label>
    <nameField>
        <displayFormat>img-{0000}</displayFormat>
        <label>Product images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/Product_images__c/fields/image__c.field-meta.xml
<CustomField>
    <fullName>image__c</fullName>
    <label>image</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

lostCTRL/force-app/main/default/objects/Product_images__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product images</relationshipLabel>
    <relationshipName>Product_images</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/classes/LCTRL_ImageHandlerTest.cls
@IsTest
public class LCTRL_ImageHandlerTest {
    
    @IsTest
    static void getMapImagesOfProductsTest(){
        Database.SaveResult productRes = Database.insert(new LCTRL_ProductBuilder().setName('testName').getProduct().getObj());
        Set<Id> productIdSet = new Set<Id>();
        productIdSet.add(productRes.getId());
        Product_images__c image = new Product_images__c();
        image.image__c = 'asd';
        image.Product__c = productRes.getId();
        insert image;

        Test.startTest();
        LCTRL_ImageHandler.getMapImagesOfProducts(productIdSet);
        LCTRL_ImageHandler.getAllImagesOfProduct(productRes.getId());
        Test.stopTest();
    }
}