lostCTRL/force-app/main/default/objects/Product_images__c/Product_images__c.object-meta.xml
<CustomObject>
    <label>Product images</label>
    <nameField>
        <displayFormat>img-{0000}</displayFormat>
        <label>Product images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/Product_images__c/fields/image__c.field-meta.xml
<CustomField>
    <fullName>image__c</fullName>
    <label>image</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

lostCTRL/force-app/main/default/objects/Product_images__c/fields/Is_main_image__c.field-meta.xml
<CustomField>
    <fullName>Is_main_image__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is main image</label>
    <type>Checkbox</type>
</CustomField>

lostCTRL/force-app/main/default/objects/Product_images__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product images</relationshipLabel>
    <relationshipName>Product_images</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/classes/LCTRL_ImageHandler.cls
/**
 * Created by cezary.bubieniec on 10.10.2022.
 */

public with sharing class LCTRL_ImageHandler {

    public static Map<String ,LCTRL_Image> getMapImagesOfProducts(Set<Id> productIdSet){
        List<Product_images__c> images = [SELECT image__c, Is_main_image__c, Product__c FROM Product_images__c WHERE Product__c IN :productIdSet AND Is_main_image__c = TRUE];
        Map<String ,LCTRL_Image> imagesReturn = new Map<String ,LCTRL_Image>();

        for(Product_images__c image: images){
            LCTRL_Image imageReturn = new LCTRL_ImageBuilder().setMain(image.Is_main_image__c).setImage(image.image__c).getImage();
            imagesReturn.put(image.Product__c, imageReturn);
        }

        return imagesReturn;
    }

    public static List<LCTRL_Image> getAllImagesOfProduct(String productId){
        List<Product_images__c> images = [SELECT image__c, Is_main_image__c, Product__c FROM Product_images__c WHERE Product__c =:productId];
        List<LCTRL_Image> imagesReturn = new List<LCTRL_Image>();

        for(Product_images__c image: images){
            LCTRL_Image imageReturn = new LCTRL_ImageBuilder().setMain(image.Is_main_image__c).setImage(image.image__c).getImage();
            imagesReturn.add(imageReturn);
        }

        return imagesReturn;
    }
}