lostCTRL/force-app/main/default/objects/CommentsProduct__c/CommentsProduct__c.object-meta.xml
<CustomObject>
    <label>Comment product</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/CommentsProduct__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Review</fullName>
                <default>true</default>
                <label>Review</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

lostCTRL/force-app/main/default/objects/CommentsProduct__c/fields/comment__c.field-meta.xml
<CustomField>
    <fullName>comment__c</fullName>
    <label>comment</label>
    <type>TextArea</type>
</CustomField>

lostCTRL/force-app/main/default/objects/CommentsProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/objects/CommentsProduct__c/fields/Star__c.field-meta.xml
<CustomField>
    <fullName>Star__c</fullName>
    <label>Star</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

lostCTRL/force-app/main/default/classes/LCTRL_SaveComment.cls
/**
 * Created by cezary.bubieniec on 17.10.2022.
 */

public with sharing class LCTRL_SaveComment {

    @AuraEnabled
    public static Boolean saveComment(String JSON){
        commentWrapper comment = commentWrapper.parse(JSON);
        CommentsProduct__c com = new CommentsProduct__c();
        com.FirstName__c = comment.name;
        com.comment__c = comment.comment;
        com.Email__c = comment.email;
        com.Product__c = comment.productId;
        com.Star__c = comment.stars;

        Database.SaveResult save = Database.insert(com);

       

        return save.isSuccess();
    }

    @AuraEnabled(cacheable=true)
    public static String getComments(String productId){
        List<CommentsProduct__c> comments = [SELECT FirstName__c, Star__c, comment__c, CreatedDate FROM CommentsProduct__c WHERE Product__c = :productId AND Approval_status__c = 'Accepted'];
        return JSON.serialize(comments);
    }
}