lostCTRL/force-app/main/default/objects/Comments__c/Comments__c.object-meta.xml
<CustomObject>
    <label>Comments</label>
    <nameField>
        <label>Comments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/Comments__c/fields/movieId__c.field-meta.xml
<CustomField>
    <fullName>movieId__c</fullName>
    <label>movieId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

lostCTRL/force-app/main/default/objects/Comments__c/fields/rating__c.field-meta.xml
<CustomField>
    <fullName>rating__c</fullName>
    <label>rating</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

lostCTRL/force-app/main/default/objects/Comments__c/fields/text__c.field-meta.xml
<CustomField>
    <fullName>text__c</fullName>
    <label>text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

lostCTRL/force-app/main/default/classes/Comments.cls
public with sharing class Comments {
    public Comments() {

    }

    @AuraEnabled
    public static string getAllCommentsFromId(String movieId){
        try {
            Comments__c[] comment = [SELECT Owner.Name, text__c, Id, rating__c FROM Comments__c WHERE movieId__c =:movieId];

            return JSON.serialize(comment);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string addComment(String movieId, String comment, Integer rating){
        try {
            Comments__c comments = new Comments__c();
            comments.text__c = comment;
            comments.movieId__c = movieId;
            comments.rating__c = rating;

            Database.SaveResult srList = Database.insert(comments, false);

            return JSON.serialize(srList);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}