lostCTRL/force-app/main/default/objects/PartsProduct__c/PartsProduct__c.object-meta.xml
<CustomObject>
    <label>PartsProduct</label>
    <nameField>
        <label>PartsProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartsProduct</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/PartsProduct__c/fields/Parts__c.field-meta.xml
<CustomField>
    <fullName>Parts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parts</label>
    <referenceTo>PartsToProducts__c</referenceTo>
    <relationshipLabel>PartsProduct</relationshipLabel>
    <relationshipName>PartsProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/objects/PartsProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>PartsProduct</relationshipLabel>
    <relationshipName>PartsProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/objects/PartsToProducts__c/PartsToProducts__c.object-meta.xml
<CustomObject>
    <label>PartsToProducts</label>
    <nameField>
        <label>PartsToProducts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartsToProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/PartsToProducts__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>SpecPart__c</referenceTo>
    <relationshipLabel>PartsToProducts</relationshipLabel>
    <relationshipName>PartsToProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/objects/SpecPart__c/SpecPart__c.object-meta.xml
<CustomObject>
    <label>SpecPart</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SpecPart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SpecPart</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/classes/LCTRL_SpecHandler.cls
/**
 * Created by cezary.bubieniec on 11.10.2022.
 */

public with sharing class LCTRL_SpecHandler {

    public static List<LCTRL_Spec> getAllSpecOfProduct(String productId){
        List<PartsProduct__c> parts = [SELECT Parts__r.Id, Parts__r.Name, Parts__r.Part__r.Name__c, Parts__r.Part__r.Id FROM PartsProduct__c WHERE Product__c = :productId];
        List<LCTRL_Spec> specs = new List<LCTRL_Spec>();

        for(PartsProduct__c part : parts){
            LCTRL_Spec spec = new LCTRL_SpecBuilder().setPart(part.Parts__r.Id,part.Parts__r.Name).setValue(part.Parts__r.Part__r.Id, part.Parts__r.Part__r.Name__c).getSpec();
            specs.add(spec);
        }
        return specs;
    }
}