lostCTRL/force-app/main/default/objects/PartsToProducts__c/PartsToProducts__c.object-meta.xml
<CustomObject>
    <label>PartsToProducts</label>
    <nameField>
        <label>PartsToProducts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartsToProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/PartsToProducts__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>SpecPart__c</referenceTo>
    <relationshipLabel>PartsToProducts</relationshipLabel>
    <relationshipName>PartsToProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/objects/SpecPart__c/SpecPart__c.object-meta.xml
<CustomObject>
    <label>SpecPart</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SpecPart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SpecPart</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/SpecPart__c/fields/Catalog__c.field-meta.xml
<CustomField>
    <fullName>Catalog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Catalog</label>
    <referenceTo>ProductCatalog</referenceTo>
    <relationshipLabel>SpecPart</relationshipLabel>
    <relationshipName>SpecPart</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/classes/LCTRL_PartServiceTest.cls
@IsTest
public class LCTRL_PartServiceTest {
    
    @IsTest
    static void getAllPartsPositive(){
        
        List<PartsToProducts__c> parts = [SELECT Id, Name, Part__r.Name__c, Part__c FROM PartsToProducts__c WHERE Name LIKE '%Ram%' OR Part__r.Name__c LIKE '%Ram%' ];
        List<LCTRL_Spec> specs = new List<LCTRL_Spec>();

        for(PartsToProducts__c part : parts){

            LCTRL_Spec spec = new LCTRL_SpecBuilder()
                                    .setPart(part.Part__c,part.Part__r.Name__c)
                                    .setValue(part.Id, part.Name)
                                    .getSpec();
            specs.add(spec);
        }

        Test.startTest();
        String dataReturn = LCTRL_PartService.getAllParts('Ram');
        Test.stopTest();

        System.assertEquals(JSON.serialize(specs), dataReturn, 'Data return neet to match.');
    }

    @IsTest
    static void getAllPartsNegative(){
        List<PartsToProducts__c> parts = [SELECT Id, Name, Part__r.Name__c, Part__c FROM PartsToProducts__c WHERE Name LIKE '%%' OR Part__r.Name__c LIKE '%%' ];
        List<LCTRL_Spec> specs = new List<LCTRL_Spec>();

        for(PartsToProducts__c part : parts){

            LCTRL_Spec spec = new LCTRL_SpecBuilder()
                                    .setPart(part.Part__c,part.Part__r.Name__c)
                                    .setValue(part.Id, part.Name)
                                    .getSpec();
            specs.add(spec);
        }

        Test.startTest();
        String dataReturn = LCTRL_PartService.getAllParts('');
        Test.stopTest();

        System.assertEquals(JSON.serialize(specs), dataReturn, 'Data return neet to match.');
    }

    @IsTest 
    static void savePart(){
        ProductCatalog catalog = new ProductCatalog();
        catalog.name = 'test';
        Database.SaveResult saveCat = Database.insert(catalog);
        SpecPart__c part = new SpecPart__c();
        part.Name__c ='asd';
        part.Catalog__c = saveCat.getId();
        Database.SaveResult saveRes = Database.insert(part);

        Test.startTest();
        String res = LCTRL_PartService.savePart(saveRes.getId(), 'value');
        Test.stopTest();
    }

    @IsTest
    static void deletePart(){
        ProductCatalog catalog = new ProductCatalog();
        catalog.name = 'test';
        Database.SaveResult saveCat = Database.insert(catalog);
        SpecPart__c part = new SpecPart__c();
        part.Name__c ='asd';
        part.Catalog__c = saveCat.getId();
        Database.SaveResult saveRes = Database.insert(part);
        PartsToProducts__c newPart = new PartsToProducts__c();
        newPart.Part__c = saveRes.getId();
        newPart.Name = 'value';
        Database.UpsertResult result = Database.upsert(newPart);

        Test.startTest();
        String rr = LCTRL_PartService.deletePart(result.getId());
        Test.stopTest();

    }

}