lostCTRL/force-app/main/default/objects/PartsToProducts__c/PartsToProducts__c.object-meta.xml
<CustomObject>
    <label>PartsToProducts</label>
    <nameField>
        <label>PartsToProducts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartsToProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/PartsToProducts__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>SpecPart__c</referenceTo>
    <relationshipLabel>PartsToProducts</relationshipLabel>
    <relationshipName>PartsToProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/objects/SpecPart__c/SpecPart__c.object-meta.xml
<CustomObject>
    <label>SpecPart</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>SpecPart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SpecPart</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/SpecPart__c/fields/Catalog__c.field-meta.xml
<CustomField>
    <fullName>Catalog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Catalog</label>
    <referenceTo>ProductCatalog</referenceTo>
    <relationshipLabel>SpecPart</relationshipLabel>
    <relationshipName>SpecPart</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/classes/LCTRL_SpecParts.cls
/**
 * Created by cezary.bubieniec on 23.09.2022.
 */

public with sharing class LCTRL_SpecParts {


    @AuraEnabled
    public static String getAllSpecsByCatalog(String catalog){
        try{
            List<SpecPart__c> specs = [SELECT Name__c, Id FROM SpecPart__c WHERE Catalog__r.Name LIKE :catalog];

            return JSON.serialize(specs);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String getAllParts(){
        try{
            List<PartsToProducts__c>  parts = [SELECT Name, Part__r.Name__c, Id FROM PartsToProducts__c];

            return JSON.serialize(parts);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}