lostCTRL/force-app/main/default/objects/OrderProduct__c/OrderProduct__c.object-meta.xml
<CustomObject>
    <label>OrderProduct</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>OrderProduct Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderProduct</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lostCTRL/force-app/main/default/objects/OrderProduct__c/fields/Adress__c.field-meta.xml
<CustomField>
    <fullName>Adress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adress</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>OrderProduct</relationshipLabel>
    <relationshipName>OrderProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/objects/OrderProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OrderProduct</relationshipLabel>
    <relationshipName>OrderProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

lostCTRL/force-app/main/default/classes/LCTRL_OrderProductService.cls
/**
 * Created by cezary.bubieniec on 17.10.2022.
 */

public with sharing class LCTRL_OrderProductService {

    @AuraEnabled
    public static String saveOrder(String JSONorder){
        return LCTRL_OrderProductHandler.saveOrder(JSONorder);
    }

    @AuraEnabled(cacheable=true)
    public static String getOrders(){
        List<OrderProduct__c> orders = [SELECT Product__r.Name, Quantity__c, CreatedDate, Adress__c  FROM OrderProduct__c];

        return JSON.serialize(orders);
    }
}